services:
  - type: web
    name: eccomi-edu-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD_PLAIN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALGO
        value: HS256
